import './index.scss'
import '../../App.scss'
import Image from '../Image'
import SlideShowDescription from '../SlideShowDescription'

import mega from '../../public/images/kollywood/mega_img_50_50.jpg'

import bhoomi from '../../public/images/kollywood/Bhoomi.jpg'
import calls from '../../public/images/kollywood/Calls.jpg'
import chakra from '../../public/images/kollywood/Chakra.jpg'
import chennayil from '../../public/images/kollywood/Chennayil_Oda_Oda.jpg'
import chidambaram from '../../public/images/kollywood/Chidambaram_Railway_Gate.jpg'
import eeswaran from '../../public/images/kollywood/Eeswaran.jpg'
import kabadadaari from '../../public/images/kollywood/Kabadadaari.jpg'
import kamali from '../../public/images/kollywood/Kamali_From_Nadukkaveri.jpg'
import kasa from '../../public/images/kollywood/kasa_kasa.jpg'
import master from '../../public/images/kollywood/Master.jpg'
import mirugaa from '../../public/images/kollywood/Mirugaa.jpg'
import naanum from '../../public/images/kollywood/Naanum_Single_Thaan.jpg'
import parris from '../../public/images/kollywood/Parris_Jeyaraj.jpg'
import pazhagiya from '../../public/images/kollywood/Pazhagiya_Naatkal.jpg'
import thallumaala from '../../public/images/kollywood/Thallumaala.jpg'
import trip from '../../public/images/kollywood/Trip.jpg'
import v from '../../public/images/kollywood/V.jpg'
const images =  [mega, bhoomi, calls, chakra, 
      chennayil, chidambaram, eeswaran, 
      kabadadaari, kamali, kasa,
      master, mirugaa, naanum,
      parris, pazhagiya, thallumaala,
      trip, v]

const media = {
  slideshow: images.map(image => <Image imageSource={image}/>),
  slideshow_descriptions: 
    ['','bhoomi','calls', 'chakra',
     'chennayil', 'chidambaram', 'eeswaran',
     'kabadadaari', 'kamali', 'kasa', 
     'master', 'mirugaa', 'naanum',
     'parris', 'pazhagiya', 'thallumaala',
     'trip', 'v']
}

const header = `Colorism in Kollywood`
const medium = `Medium: archival ink on paper`
const size = `Size: 3' x 3' `
const description =  `
Description: Growing up watching Tamil films, the skin tone of the female 
lead always seemed lighter than the male lead even though they’re both South Indian. If we look at the faces found across many Tamil films, are the lighter ones women? I investigate this in a systematic way using code. This piece is generated by automatically segmenting faces out of 15 Tamil movies released over the last two years. The faces are sorted onto the grid using an estimate of their skin tone. Down to up is lighter to darker skin tones and left to right is greyer to saturated skintones. I encourage the viewer to look at the grid and draw their own conclusions on whether there is a pattern between gender and skin tone.
`


const Kollywood = () => {
  return (
    <div>
      <div className='header-slideshow'>
        {header}
      </div>
      <SlideShowDescription media = {media} item1 = {medium} item2 = {size} description ={description}/>
    </div>
  )
}

export default Kollywood